# Production Dockerfile
FROM node:alpine AS production

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm i
RUN npm i -g @nestjs/cli

# Copy the built application code
COPY . .

RUN npm run build

# Start the application in production mode
CMD ["node", "dist/main.js"]